export const countriesConfig = [
  { value: `"Australia" in (countries.country)`, title: "Australia" },
  { value: `"Canada" in (countries.country)`, title: "Canada" },
  { value: `"China" in (countries.country)`, title: "China" },
  { value: `"Austria" in (countries.country)`, title: "Austria" },
  { value: `"Belgium" in (countries.country)`, title: "Belgium" },
  { value: `"Bulgaria" in (countries.country)`, title: "Bulgaria" },
  { value: `"Croatia" in (countries.country)`, title: "Croatia" },
  { value: `"Cyprus" in (countries.country)`, title: "Cyprus" },
  { value: `"Czech Republic" in (countries.country)`, title: "Czech Republic" },
  { value: `"Denmark" in (countries.country)`, title: "Denmark" },
  { value: `"Estonia" in (countries.country)`, title: "Estonia" },
  { value: `"Finland" in (countries.country)`, title: "Finland" },
  { value: `"France" in (countries.country)`, title: "France" },
  { value: `"Germany" in (countries.country)`, title: "Germany" },
  { value: `"Greece" in (countries.country)`, title: "Greece" },
  { value: `"Hungary" in (countries.country)`, title: "Hungary" },
  { value: `"Ireland" in (countries.country)`, title: "Ireland" },
  { value: `"Italy" in (countries.country)`, title: "Italy" },
  { value: `"Latvia" in (countries.country)`, title: "Latvia" },
  { value: `"Lithuania" in (countries.country)`, title: "Lithuania" },
  { value: `"Luxembourg" in (countries.country)`, title: "Luxembourg" },
  { value: `"Malta" in (countries.country)`, title: "Malta" },
  { value: `"Netherlands" in (countries.country)`, title: "Netherlands" },
  { value: `"Poland" in (countries.country)`, title: "Poland" },
  { value: `"Portugal" in (countries.country)`, title: "Portugal" },
  { value: `"Romania" in (countries.country)`, title: "Romania" },
  { value: `"Slovakia" in (countries.country)`, title: "Slovakia" },
  { value: `"Slovenia" in (countries.country)`, title: "Slovenia" },
  { value: `"Spain" in (countries.country)`, title: "Spain" },
  { value: `"Sweden" in (countries.country)`, title: "Sweden" },
  { value: `"Japan" in (countries.country)`, title: "Japan" },
  { value: `"South Korea" in (countries.country)`, title: "South Korea" },
  { value: `"Malaysia" in (countries.country)`, title: "Malaysia" },
  { value: `"New Zealand" in (countries.country)`, title: "New Zealand" },
  { value: `"Philippines" in (countries.country)`, title: "Philippines" },
  { value: `"Taiwan" in (countries.country)`, title: "Taiwan" },
  { value: `"United States of America" in (countries.country)`, title: "United States of America" },
  { value: `"Norway" in (countries.country)`, title: "Norway" },
];
